name: Mostrar hola
on:
  push:
   ranches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Escribir mensaje en la pantalla
      run: |
        echo " hoy es $sysdate"
        echo "Hola desde el runner de github action"